export type Project = {
  slug: string;
  title: string;
  category: 'Mechanical Design' | 'Robotics';
  label: string;
  date: string;
  summary: string;
  challenge: string;
  approach: string[];
  notes?: { title: string; text: string }[];
  media?: { type: 'image' | 'video'; src: string; alt: string; caption: string };
  additionalMedia?: { type: 'image' | 'video'; src: string; alt: string; caption: string }[];
};

export const projects: Project[] = [
  { slug: 'quadruped', title: 'Quadruped robot', category: 'Robotics', label: 'Independent project', date: 'May 2026 - Present', summary: 'Developing a compact 8-DOF quadruped robot with custom geared actuation.', challenge: 'Build a compact legged platform with actuators sized for the required joint torque and loading.', approach: ['Designed a 5:1 planetary gearbox delivering 3.6 N-m of joint torque', 'Reduced actuator cost by 20% through the gearbox design', 'Sized gears and actuators using joint-torque, gear-reduction, motor-loading, and strength-to-geometry calculations'], notes: [{ title: 'Actuation', text: 'The robot uses custom geared actuation across its eight degrees of freedom.' }, { title: 'Planetary gearbox', text: 'The 5:1 planetary gearbox targets 3.6 N-m of joint torque while reducing actuator cost by 20%.' }, { title: 'Sizing calculations', text: 'Gear and actuator sizing accounts for joint torque, gear reduction, motor loading, and strength-to-geometry requirements.' }] },
  { slug: 'inverted-pendulum', title: 'Two-wheeled inverted pendulum', category: 'Robotics', label: 'PID Controls Project', date: 'Course project', summary: 'A two-wheeled robot that balances itself with onboard sensor feedback.', challenge: 'Keep the robot upright in a small area while still allowing controlled motion.', approach: ['Used pitch for balance control', 'Used yaw for heading and roll as a stability check', 'Tuned PID gains through repeated tests', 'Added target-distance control for repeatable moves', 'Lowered the center of mass and moment of inertia through mechanical revisions'], notes: [{ title: 'Control inputs', text: 'Pitch drove the balance loop. Yaw was used for heading during motion. Roll was monitored for instability caused by uneven loading or disturbance.' }, { title: 'Mechanical changes', text: 'We lowered the center of mass and reduced the moment of inertia. The robot was less susceptible to tipping moments and responded more quickly to correction.' }, { title: 'Distance target', text: 'A target distance gave each move a defined endpoint. That made travel more repeatable and improved the final control behavior.' }, { title: 'Outcome', text: 'The final robot balanced while moving and received the class award for Best Controls.' }], media: { type: 'video', src: '/projects/inverted-pendulum.mp4', alt: 'Two-wheeled inverted pendulum balancing demonstration', caption: 'Self-balancing demonstration of the two-wheeled inverted pendulum controller.' } },
  { slug: 'path-planning', title: 'Path planning', category: 'Robotics', label: 'Wavefront Path Planning Project', date: 'Course project', summary: 'A map-based planner that finds a route between a start point and a goal.', challenge: 'Find a short, accurate route through a known course.', approach: ['Mapped obstacles and open space', 'Planned routes around obstacles', 'Tracked the robot with wheel encoders and IMU data'], notes: [{ title: 'Map', text: 'The course was converted into a configuration space that marked obstacles and valid travel areas.' }, { title: 'Planning', text: 'The path balanced route length, obstacle clearance, and final position accuracy. The wavefront plot shows how the goal and obstacles shaped the route.' }, { title: 'Execution', text: 'The robot followed the path using wheel encoders and IMU data.' }], media: { type: 'video', src: '/projects/path-planning.mp4', alt: 'Path-planning demonstration', caption: 'Robot following the planned route through the course.' }, additionalMedia: [{ type: 'image', src: '/projects/wavefront.png', alt: 'Wavefront planning visualization', caption: 'Wavefront map used to plan a route around obstacles.' }] },
  { slug: 'localization', title: 'Probabilistic localization', category: 'Robotics', label: 'Probabilistic Localization Project', date: 'Course project', summary: 'A Bayes-probability model for locating a robot on a circular track with imperfect sensor data.', challenge: 'Estimate position when the robot cannot measure its exact location directly.', approach: ['Split the circular track into possible states', 'Stored a Bayes probability for each state', 'Updated the distribution after movement and sensor readings', 'Selected the most likely position', 'Tested the model after removing an obstacle from the course'], notes: [{ title: 'Bayes model', text: 'Each position on the circular track was a discrete state with its own probability. Bayes updates combined the previous belief with motion and sensor evidence.' }, { title: 'Motion update', text: 'After the robot moved, the probability distribution shifted to match the expected movement and its error.' }, { title: 'Sensor update', text: 'Sensor readings increased the probability of matching positions and reduced the probability of positions that did not match.' }, { title: 'Changed-obstacle test', text: 'We removed an obstacle from the course to test whether the model could handle a changed environment and recover from sensor evidence that no longer matched the original map.' }], media: { type: 'video', src: '/projects/localization.mp4', alt: 'Probabilistic localization demonstration', caption: 'Robot localizing along the circular course.' } },
  { slug: 'amazon-suitcase', title: 'Smart suitcase locking system', category: 'Mechanical Design', label: 'Amazon project', date: 'Prototype development', summary: 'A phone-connected suitcase lock with tracking and keyless access.', challenge: 'Fit a reliable lock into a tight package with limited power and a path to high-volume production.', approach: ['Led the tracking and keyless-access work', 'Designed an NFC-powered electromechanical lock', 'Printed and revised enclosure prototypes', 'Built the PCB and actuator system', 'Ran structured performance tests'], notes: [{ title: 'Current key-lock mechanism', text: 'The prototype uses a spring-loaded lock. The spring is held back in the locked position and released during the unlock sequence.' }, { title: 'Planned worm-gear redesign', text: 'The next design uses a worm gear so the user does not need to lock the suitcase manually. After unlocking, one full rotation would lock it again after 10 seconds.' }, { title: 'Production constraints', text: 'The design had to fit tight space and power limits while remaining practical to manufacture at volume.' }, { title: 'Outcome', text: 'We presented the prototype at an internal conference and secured funding to continue development.' }], media: { type: 'video', src: '/projects/amazon-suitcase.mp4', alt: 'Smart suitcase locking system demonstration', caption: 'Video demonstration of unlocking and locking the suitcase.' }, additionalMedia: [{ type: 'image', src: '/projects/amazon-cad.jpg', alt: 'Smart suitcase locking system CAD view', caption: 'CAD view of the locking mechanism. Springs are shown in red, with their force directions indicated.' }, { type: 'image', src: '/projects/amazon-exterior.jpeg', alt: 'Smart suitcase locking system exterior view', caption: 'Exterior prototype view of the locking mechanism installed on the suitcase.' }, { type: 'image', src: '/projects/amazon-interior.png', alt: 'Smart suitcase locking system interior view', caption: 'Interior prototype view showing the locking mechanism and supporting electronics.' }] },
  { slug: 'collapsible-camping-chair', title: 'Collapsible camping chair', category: 'Mechanical Design', label: 'Chair Design Project', date: 'Design and prototyping', summary: 'A lightweight camping chair designed to carry a seated load, pack down quickly, and stay stable on uneven ground.', challenge: 'Build a compact chair that supports a seated person while remaining easy to carry and assemble outdoors.', approach: ['Built the frame from aluminum tubing and 3D-printed connectors', 'Used canvas for the seat and backrest, with elastic cord to guide assembly', 'Added wider notched feet to reduce slipping and sinking on soft ground', 'Used hand calculations and FEA to identify and revise high-stress connections'], notes: [{ title: 'Hand calculations', text: 'We split the symmetric frame into half-load free-body diagrams and calculated reactions, bending moments, and member stresses.' }, { title: 'FEA model', text: 'The model used aluminum supports and PLA connectors. The fabric was replaced with estimated loads because it was not modeled directly.' }, { title: 'Design revision', text: 'The analysis showed the highest bending near the legs and connectors, so we increased the connector radius to better support torque.' }, { title: 'Validation', text: 'We compared the fixed-foot FEA boundary condition with more realistic ground contact, then load-tested the assembled chair.' }], media: { type: 'image', src: '/projects/camping-chair-fea.png', alt: 'Finite element analysis of the collapsible camping chair', caption: 'FEA setup and von Mises stress result for the chair frame and 3D-printed connectors.' }, additionalMedia: [{ type: 'image', src: '/projects/camping-chair-hand-calcs.png', alt: 'Hand calculations for the collapsible camping chair', caption: 'Hand calculations used to estimate frame reactions, bending moments, and member stresses.' }, { type: 'image', src: '/projects/camping-chair-load-test.png', alt: 'Load test of the collapsible camping chair', caption: 'Load test of the chair outdoors.' }, { type: 'image', src: '/projects/camping-chair-folded.png', alt: 'Folded collapsible camping chair', caption: 'Chair folded for transport.' }] },
  { slug: 'usar', title: 'Urban search and rescue robot', category: 'Robotics', label: 'USAR Project', date: 'Course project', summary: 'A compact teleoperated robot for a mock-disaster course with mapping and manipulation tasks.', challenge: 'Build a robot that can handle stairs, ramps, rubble, and tight spaces while giving the operator usable camera control.', approach: ['Built a compact chassis for uneven terrain', 'Added electrical components to improve capability', 'Used live camera feedback for teleoperation', 'Tested with low light, signal loss, delay, and limited visibility'], notes: [{ title: 'Mechanical design', text: 'The chassis was built to stay compact while handling stairs, ramps, rubble, and restricted spaces.' }, { title: 'Teleoperation', text: 'Camera feedback and movement controls were set up for clear, predictable operation in a cluttered course.' }, { title: 'Testing conditions', text: 'We tested around communication delay, intermittent control signal, low light, obstacles, and a limited camera view.' }], media: { type: 'video', src: '/projects/amazon-movement-controls.mp4', alt: 'USAR movement controls with camera demonstration', caption: 'Camera-assisted teleoperation demonstration of the USAR robot.' }, additionalMedia: [{ type: 'image', src: '/projects/robot-gearing-class.png', alt: 'USAR robot gearing image', caption: 'Gearing layout used in the USAR robot design.' }] },
];

export function getProject(slug: string) { return projects.find((project) => project.slug === slug); }
