export type Project = {
  slug: string;
  title: string;
  category: 'Mechanical Design' | 'Robotics';
  label: string;
  date: string;
  summary: string;
  challenge: string;
  approach: string[];
  notes?: { title: string; text: string }[];
  media?: { type: 'image' | 'video'; src: string; alt: string };
  additionalMedia?: { type: 'image' | 'video'; src: string; alt: string }[];
};

export const projects: Project[] = [
  { slug: 'quadruped', title: 'Quadruped robot', category: 'Robotics', label: 'Independent project', date: 'In progress', summary: 'A modular legged robotics platform for investigating mechanical design, actuator integration, controls, and gait testing.', challenge: 'Build a testable legged platform that can support iterative work across the mechanical and controls stack.', approach: ['Mechanical architecture and leg design', 'Actuator selection and integration', 'Control system development', 'Gait testing and iteration'], media: { type: 'image', src: '/projects/quadruped.png', alt: 'Quadruped robotics prototype' } },
  { slug: 'inverted-pendulum', title: 'Two-wheeled inverted pendulum', category: 'Robotics', label: 'CMU General Robotics / Controls', date: 'Course project', summary: 'A two-wheeled self-balancing robot that uses onboard sensor feedback to remain upright.', challenge: 'Create an inverted pendulum capable of balancing in a small area while responding predictably to position commands.', approach: ['Used pitch as the primary balance signal for the feedback controller', 'Used yaw to manage heading during motion and roll as a stability observation', 'Tuned proportional, integral, and derivative gains through repeated tests', 'Added a target-distance command rather than relying on open-ended motion'], notes: [{ title: 'Orientation and balance', text: 'The controller used the robot’s orientation as feedback. Pitch was the primary error signal for keeping the body upright, while yaw informed heading during commanded motion. Roll was monitored as a stability check when the robot encountered asymmetry or disturbance.' }, { title: 'Distance target', text: 'Adding a target distance gave the controller a concrete endpoint for motion. This reduced drift and made position changes more repeatable than a simple drive command, substantially improving the final behavior.' }, { title: 'Outcome', text: 'The final system combined balancing and controlled travel, and received the class award for Best Controls.' }], media: { type: 'video', src: '/projects/inverted-pendulum.mp4', alt: 'Two-wheeled inverted pendulum balancing demonstration' } },
  { slug: 'path-planning', title: 'Path planning', category: 'Robotics', label: 'CMU General Robotics / Planning', date: 'Course project', summary: 'A planner for finding a route through a known map from a given start point to a finish point.', challenge: 'Determine an accurate, efficient path through a known course while accounting for final-position error and path length.', approach: ['Represented the environment as a navigable configuration space', 'Used map structure to identify traversable routes around obstacles', 'Executed the selected route with encoder-based odometry and IMU-informed dead reckoning'], notes: [{ title: 'World representation', text: 'The planning problem begins by converting the known course into a configuration space. Obstacles and accessible regions are represented so that the planner can reason about where the robot can safely travel.' }, { title: 'Planning tradeoff', text: 'The route must balance path length with the ability to reach the final position accurately. The wavefront visualization documents how obstacle clearance and the final goal shape the selected path.' }, { title: 'Execution', text: 'The planner only provides a route. To follow it, the robot estimates motion from wheel encoders and uses inertial information to limit accumulated error during dead reckoning.' }], media: { type: 'video', src: '/projects/path-planning.mp4', alt: 'Path-planning demonstration' }, additionalMedia: [{ type: 'image', src: '/projects/wavefront.png', alt: 'Wavefront planning visualization' }] },
  { slug: 'localization', title: 'Probabilistic localization', category: 'Robotics', label: 'CMU General Robotics / Localization', date: 'Course project', summary: 'A discrete belief-state model that estimates a robot’s position along a circular path from imperfect observations.', challenge: 'Determine the robot’s most likely location when an exact position cannot be observed directly.', approach: ['Represented possible positions as a probability distribution around the circular track', 'Applied motion updates to predict how the distribution changes as the robot moves', 'Applied observation updates to reweight likely positions from environmental information', 'Used the most likely state while retaining uncertainty in the full distribution'], notes: [{ title: 'Model', text: 'Localization was represented as a discrete belief state: each possible position along the circular path holds a probability rather than being treated as certainly correct or incorrect.' }, { title: 'Prediction update', text: 'When the robot moves, the model shifts the belief distribution according to the commanded motion and expected uncertainty. This keeps the estimate useful even when motion is imperfect.' }, { title: 'Measurement update', text: 'Environmental information is used to reweight the distribution. Positions consistent with the observation become more likely; inconsistent positions are reduced, leaving an updated estimate of the robot’s location.' }], media: { type: 'video', src: '/projects/localization.mp4', alt: 'Probabilistic localization demonstration' } },
  { slug: 'amazon-suitcase', title: 'Smart suitcase locking system', category: 'Mechanical Design', label: 'Amazon project', date: 'Prototype development', summary: 'A smart suitcase locking system for phone-based tracking and keyless access.', challenge: 'Develop a lock that supports a useful connected-suitcase experience while meeting severe space, power, manufacturability, and production constraints.', approach: ['Led development of the phone-based tracking and keyless-access concept', 'Designed an NFC-powered electromechanical lock for battery-free operation and high-volume production', 'Rapidly prototyped enclosure designs through FDM printing', 'Built a custom PCB and actuator architecture', 'Validated the system through structured performance testing'], notes: [{ title: 'Locking architecture', text: 'The locking system combined NFC with an electromechanical mechanism, allowing keyless access without requiring a dedicated battery in the lock.' }, { title: 'Design for production', text: 'Enclosure and internal architecture decisions were evaluated against tight packaging volume, power limits, manufacturability, and the needs of high-volume production.' }, { title: 'Outcome', text: 'The prototype was presented at an internal conference and secured funding for continued development.' }], media: { type: 'video', src: '/projects/amazon-suitcase.mp4', alt: 'Smart suitcase locking system demonstration' }, additionalMedia: [{ type: 'image', src: '/projects/amazon-cad.jpg', alt: 'Smart suitcase locking system CAD view' }, { type: 'image', src: '/projects/amazon-exterior.jpeg', alt: 'Smart suitcase locking system exterior view' }, { type: 'image', src: '/projects/amazon-interior.png', alt: 'Smart suitcase locking system interior view' }] },
  { slug: 'usar', title: 'Urban search and rescue robot', category: 'Robotics', label: 'CMU General Robotics / USAR', date: 'Course project', summary: 'A compact, teleoperated robot designed to navigate a mock-disaster environment and complete mapping and manipulation tasks.', challenge: 'Create a robust robot that can traverse stairs, ramps, rubble, and tight spaces while maintaining reliable camera-assisted operator control.', approach: ['Designed a compact, rugged mechanical platform for uneven terrain and confined environments', 'Integrated electrical components to extend robot capability', 'Built a user-focused teleoperation workflow around live camera feedback', 'Tested operation under limited visibility, communication delay, and intermittent signal conditions'], notes: [{ title: 'Mechanical approach', text: 'The design emphasis was compactness and robustness: enough mobility to negotiate stairs, ramps, rubble, and constrained spaces without making the platform difficult to operate or service.' }, { title: 'Operator interface', text: 'The teleoperated workflow centered on camera feedback and deliberate movement controls. The operator needs usable visibility and predictable response when navigating a cluttered environment.' }, { title: 'Failure-aware testing', text: 'The system was designed and evaluated with realistic constraints in mind: communication delay, intermittent control, limited camera field of view, low light, obstacles, and restricted mobility.' }], media: { type: 'video', src: '/projects/amazon-movement-controls.mp4', alt: 'USAR movement controls with camera demonstration' }, additionalMedia: [{ type: 'image', src: '/projects/robot-gearing-class.png', alt: 'USAR robot gearing image' }] },
];

export function getProject(slug: string) { return projects.find((project) => project.slug === slug); }
